<?php

namespace JBJ\Workflow\StateMachine\Device;

use Symfony\Workflow\WorkflowInterface;

/**
 * OutputDevice
 *
 * Generated by MemoryDevice when requested.
 *
 * Output devces contain output combinational login, using a workflow current
 * state and possibly a set of input signals.
 *
 * This is useful to both a workflow and a state machine implementation.
 *
 * The workflow can have a concept of general state (or state categorized by a
 * marking(s)). A workflow implementation will not have the concept of input
 * signals.This type of categorization inside a workflow would likely be executed
 * by a state machine, but can be optimized into an implementation specific code.
 *
 * An output device is a read-only collection. The entire collection is the output
 * for the current state/input signals combination. When the state changes, so
 * will the output array.
 *
 * For example: you could output a list or menu that will be specific to a given
 * state.
 *
 * Contextual application output is a primary function of an output device.
 */
class OutputDevice extends Device
{
    public function __construct(array $elements = [], string $name = '')
    {
        parent::__construct($elements, $name);
    }
}
